# Generated by Django 5.1.1 on 2024-10-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='campana',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
