# Generated by Django 5.1.1 on 2024-10-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_campana_fecha_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campana',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
