# Generated by Django 5.1.1 on 2024-10-02 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_campana_fecha_inicio'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='campana',
            table='api_campanas',
        ),
    ]
