# Generated by Django 5.1.1 on 2024-10-03 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_campana_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='campana',
            table='campanas',
        ),
    ]
