# Generated by Django 5.1.1 on 2024-10-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_campana_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='campana',
            name='presupuesto',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campana',
            name='tamaño_audiencia',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campana',
            name='tipo_campana',
            field=models.CharField(choices=[('email', 'Email Marketing'), ('google_ads', 'Google Ads'), ('social_media', 'Social Media'), ('banner', 'Banner Advertising')], default='email', max_length=50),
        ),
    ]
